server.port=8089
spring.application.name=ecommerce-mail-service
spring.output.ansi.enabled=ALWAYS

# === OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180
spring.security.oauth2.client.registration.ecommerce-mail-service.provider=spring
spring.security.oauth2.client.registration.ecommerce-mail-service.client-id=ecommerce-mail-service
spring.security.oauth2.client.registration.ecommerce-mail-service.client-secret=mail-client-secret
spring.security.oauth2.client.registration.ecommerce-mail-service.client-authorization-method=client_secret_basic
spring.security.oauth2.client.registration.ecommerce-mail-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.ecommerce-mail-service.scope=admin
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:8180
spring.security.oauth2.client.provider.spring.authorization-uri=http://localhost:8180/oauth2/authorize

# === Spring mail ===
spring.mail.from=no-reply@ecommerce.com
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# === Kafka ===
spring.kafka.bootstrap-servers=http://localhost:9094

# === Database ===
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_mail_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# === External
services.customer-service.url=http://localhost:8081/api/v1/customers
services.order-service.url=http://localhost:8086/api/v1/orders