server.port=8090
spring.application.name=ecommerce-catalog-service
spring.output.ansi.enabled=ALWAYS

# === OAuth2 ===
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180
spring.security.oauth2.client.registration.ecommerce-catalog-service.provider=spring
spring.security.oauth2.client.registration.ecommerce-catalog-service.client-id=ecommerce-catalog-service
spring.security.oauth2.client.registration.ecommerce-catalog-service.client-secret=catalog-client-secret
spring.security.oauth2.client.registration.ecommerce-catalog-service.client-authorization-method=client_secret_basic
spring.security.oauth2.client.registration.ecommerce-catalog-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.ecommerce-catalog-service.scope=admin
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:8180
spring.security.oauth2.client.provider.spring.authorization-uri=http://localhost:8180/oauth2/authorize

# === Redis Cache ===
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# === Actuator ===
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# === Microservices ===
services.inventory-service.scheme=http
services.inventory-service.host=localhost
services.inventory-service.port=8082
services.inventory-service.products-path=/api/v1/products/category
services.inventory-service.categories-path=/api/v1/categories/subcategories
