server:
  port: 8088
logging:
  group:
    infra-services: com.felipe.ecommerce_shipping_service.infrastructure.services.ShipmentSchedulerService
  level:
    infra-services: debug
spring:
  application.name: ecommerce-shipping-service
  output.ansi.enabled: ALWAYS

  # === OAuth2 ====
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180

  # === Database ===
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_shipping_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  # === Kafka ===
  kafka:
    bootstrap-servers: http://localhost:9094

# === Actuator ===
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/