package com.felipe.ecommerce_inventory_service.infrastructure.persistence.repositories;

import com.felipe.ecommerce_inventory_service.infrastructure.persistence.entities.BrandEntity;
import com.felipe.ecommerce_inventory_service.infrastructure.persistence.entities.ModelEntity;
import com.felipe.ecommerce_inventory_service.testutils.DataMock;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles(value = "test")
public class ModelRepositoryTest {

  @Autowired
  EntityManager entityManager;

  @Autowired
  ModelRepository modelRepository;

  private DataMock dataMock;

  @BeforeEach
  void setUp() {
    this.dataMock = new DataMock();
  }

  @Test
  @DisplayName("findAllByBrandIdReturnsFoundModelsList - Should find all models of a brand and return it as a list of ModelEntity")
  void findAllByBrandIdReturnsFoundModelsList() {
    // Setting entities id to null to be automatically generated by the EntityManager
    List<BrandEntity> brands = this.dataMock.getBrandsEntity()
      .stream()
      .map(entity -> BrandEntity.mutate(entity).id(null).build())
      .toList();

    List<ModelEntity> models = this.dataMock.getModelsEntity()
      .stream()
      .map(entity -> ModelEntity.mutate(entity).id(null).build())
      .toList();

    // Persisting the entities in the test database
    brands.forEach(this.entityManager::persist);
    models.forEach(this.entityManager::persist);

    final Long brandId = 1L; // 'logitech' brand id

    List<ModelEntity> allModels = this.modelRepository.findAllByBrandId(brandId);

    assertThat(allModels.size()).isEqualTo(3);
    assertThat(allModels.stream().map(model -> model.getBrand().getId()).toList()).containsOnly(brandId);
  }
}
